### ISSUE TITLE
ModuleNotFoundError: No module named 'deepsense'

### ISSUE THREAD

**Issue by poteman** [neptune-ml/open-solution-home-credit#154] opened 2018-07-23 16:19 UTC
There are two things that will make the processing of your issue faster:
1. Make sure that you are using the latest version of the code,
1. In case of bug issue, it would be nice to provide more technical details such like execution command, error message or script that reproduces your bug.
#

Thanks!

Kamil & Jakub,

*core contributors to the [minerva.ml](https://minerva.ml)*

**Comment by kamil-kaczmarek** [comment] 2018-07-23 16:32
Hi @poteman,

Please install requirements first: `pip3 install -r requirements.txt` or `pip3 install neptune-cli`.

This will solve your problem :smile:

**Comment by KunlinY** [comment] 2018-08-10 16:31
Hi @kamil-kaczmarek , I hv installed all the requirements, but there is still no 'deepsense', is there something missing?

**Comment by PinkhamCreeker** [comment] 2018-08-11 23:46
I do not get this error when running on my machine, but DO get it when running on AWS.  Oddly after I install the requirements, some of them are still not available when I do a 
pip freeze
on the AWS machine. ??

**Comment by kamil-kaczmarek** [comment] 2018-08-12 14:00
Hi @KunlinY,

Please make sure that you did `pip3 install neptune-cli` -> this installs deepsense :smiley: Note, that we only support Linux machines at this point.

Please let me know if it helps

Cheers,
Kamil

**Comment by kamil-kaczmarek** [comment] 2018-08-12 14:04
Hi @PinkhamCreeker, interesting :thinking:...

I didn't observe anything like this. Are you sure that on your AWS you have `python3.5` and ran: `pip3 install neptune-cli`? You need to have all Python packages installed on your AWS machine to run this code.

Two actions for you:
1. Please let me know if the above holds true.
2. Paste your python version, machine details and `pip freeze` output in your comment here.

Best,
Kamil

**Comment by PinkhamCreeker** [comment] 2018-08-12 15:32
Thank you for your response!
It is working now.  Part of the problem is that I am a noob at Python.
What got it going was I had to use pip instead of pip3 to make the installations.  Not sure why, maybe something to do with the AMI I chose.
Also, thanks for your very interesting work!

**Comment by kamil-kaczmarek** [comment] 2018-08-13 10:07
Nice to hear @PinkhamCreeker.

Best of luck with the competition,

Kamil

**Comment by dujijundavid** [comment] 2018-08-28 19:30
Thanks for the great platform！


I tend to stuck at uninstall 'psutil',  after I used "pip3 install -r requirements.txt"

Installing collected packages: psutil, neptune-cli, numpy, pandas, ipython, steppy, steppy-toolkit, category-encoders, lightgbm
  Found existing installation: psutil 5.2.2

And manually remove psutil seems not working..

**Comment by kamil-kaczmarek** [comment] 2018-09-22 17:52
Since the competitions is now closed on Kaggle, I'm closing this as well :)

**Closed by kamil-kaczmarek** 2018-09-22 17:52 UTC
